export const GET_RADIO_STATIONS_REQUESTED = 'GET_RADIO_STATIONS_REQUESTED';
export const GET_RADIO_STATIONS_SUCCESS = 'GET_RADIO_STATIONS_SUCCESS';
export const GET_RADIO_STATIONS_FAILED = 'GET_RADIO_STATIONS_FAILED';
